version: '3'

services:

  be-mock-api:
    build:
      context: .
    network_mode: host
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DB_NAME_MONGO: API_MOCK
      MONGO_CONNECTION: mongodb://localhost:27017/

  mongo:
    image: mongo
    volumes:
      - $HOME/mongo:/data/db
    ports:
      - 27017:27017
