# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gateway.protocol_buffers.generated_files import simulator_services_pb2 as gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2


class SimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.startDeviceSimulation = channel.unary_unary(
                '/Simulator/startDeviceSimulation',
                request_serializer=gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2.entityId.SerializeToString,
                response_deserializer=gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2.response.FromString,
                )


class SimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def startDeviceSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'startDeviceSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.startDeviceSimulation,
                    request_deserializer=gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2.entityId.FromString,
                    response_serializer=gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def startDeviceSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/startDeviceSimulation',
            gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2.entityId.SerializeToString,
            gateway_dot_protocol__buffers_dot_generated__files_dot_simulator__services__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
