name: Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  run-tests:
    name: Run test

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python version ${{ matrix.python-version }} to test
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-docker.txt ]; then pip install -r requirements-docker.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: run pytest
        run: pytest
            